refactor broker deployment
wiz-sec/charts pull request #100
Opened 2023-04-20 12:06 UTC by itshacki

refactor broker deployment

2023-04-20 12:25 UTC, yarinm requested changes

2023-04-20 12:25 UTC, yarinm commented on wiz-kubernetes-connector/Chart.yaml
> +
You also need to bump the actual chart version

2023-04-20 12:25 UTC, yarinm commented on wiz-broker-v2/.helmignore
> +# Patterns to ignore when building packages.
I'm not sure we really need a `v2` dedicated chart here,

You could just apply your changes to the existing chart and bump its version.

Consult with @barmagnezi regarding this change as well

2023-04-23 12:17 UTC, yarinm submitted a review, later dismissed

2023-05-16 08:51 UTC, lir-wiz commented
Please do not merge yet

2025-09-17 07:29 UTC, closed without merging