WZ-35110: Add support for custom root CA
wiz-sec/charts pull request #271
Opened 2024-02-28 13:37 UTC by eyal-moscovici

2024-02-29 11:30 UTC, yarinm requested changes

2024-02-29 11:30 UTC, yarinm commented on git-proxy/templates/deployment.yaml
> +        - name: custom-cert-ca
What about conditionally adding theis and the env var?

2024-03-03 14:26 UTC, ariknem commented
much better :)

2024-03-05 07:55 UTC, yarinm approved these changes

2024-03-06 08:41 UTC, merged